### ISSUE TITLE
[CRASH] Status screen crashes when clicking refresh

### ISSUE THREAD

**Issue by Ulydev** [CoronaTeam/CoronaGame#109]
**Steps to reproduce:**
Navigate to status screen from MainActivity, click on Refresh.

**Trace:**
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ch.epfl.sdp, PID: 6173
    java.lang.ClassCastException: java.util.HashMap cannot be cast to com.google.firebase.firestore.QuerySnapshot
        at ch.epfl.sdp.contamination.ConcreteDataReceiver$3.onCallback(ConcreteDataReceiver.java:168)
        at ch.epfl.sdp.firestore.FirestoreInteractor$2.onSuccess(FirestoreInteractor.java:164)
        at ch.epfl.sdp.firestore.FirestoreInteractor$2.onSuccess(FirestoreInteractor.java:161)
        at ch.epfl.sdp.firestore.FirestoreInteractor.lambda$onCompleteListenerBuilder$2(FirestoreInteractor.java:185)
        at ch.epfl.sdp.firestore.-$$Lambda$FirestoreInteractor$g61NM5wNwZ7L3LpHJvp4aCbf2tc.onComplete(lambda)
        at com.google.android.gms.tasks.zzj.run(Unknown Source)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by Ulydev** [comment]
duplicate of #100
